package bt.unicamp.ft.m183711_v188110.vista_me;

import bt.unicamp.ft.m183711_v188110.vista_me.entities.Product;
import bt.unicamp.ft.m183711_v188110.vista_me.enumerations.e_Sexo;

public class Products {

     public static Product[] products= {
            new Product("CAMISA POLO LACOSTE L.12.12 MASCULINA EDIÇÃO LIMITADA DE ANIVERSÁRIO DE 85 ANOS EM PIQUÉ DE LÃ","Elegante design esportivo para esta camisa polo L.12.12 em piqué de lã. Uma exclusiva peça de edição limitada em comemoração ao aniversário de 85 anos da tradicional camisa polo Lacoste. \n Piqué de lã unicolor \n Gola polo com dois botões \n Classic fit \n Acabamentos canelados \n Crocodilo de couro bordado no peito \n Tecido principal: Lã (100%) / Punhos canelados: Lã (98%), Elastano (2%)",R.drawable.product1 ,100,10, e_Sexo.masculino),
            new Product("POLO LACOSTE SPORT GOLF MASCULINA EM PIQUÉ TÉCNICO COM COLOR BLOCK","Feita em petit piqué ultra-dry, esta polo Lacoste Sport Golf apresenta um design característico com color blocks. Entre no ritmo com uma vantagem técnica.\n Gola canelada impermeável com três botões \n Piqué técnico ventilado, resistente e ultra-dry \n Color Block \n Palavra Lacoste em relevo na gola \n Transfer do crocodilo, na cor verde \n COTTON/POLYESTER (58%-42%)",R.drawable.product2 ,100,10,e_Sexo.masculino),
            new Product("CAMISA POLO LACOSTE SPORT TENNIS MASCULINA EM PIQUÉ TÉCNICO COM FAIXAS COLORIDAS","Feita em piqué técnico ultraventilado, esta camisa polo Lacoste Sport Tennis ostenta um design gráfico da marca no peito. Ideal para a sua próxima competição. \n Piqué técnico ventilado, resistente, ultra-dry e run-resistant \n Gola polo canelada com dois botões \n Faixas contrastantes bicolores no peito \n Palavra Lacoste da parte detrás da gola e na manga direita \n Transfer verde do crocodilo no peito \n Tecido principal: Poliéster (100%) / Gola: Poliéster (98%), Elastano (2%)",R.drawable.product3 ,100,10,e_Sexo.masculino),
            new Product("POLO LACOSTE SPORT TENNIS MASCULINA EM PIQUÉ TÉCNICO COM COLOR BLOCK","Um color block gráfico destaca o resistente tecido desta polo Lacoste Sport Tennis. Seja qual for o seu esporte, esta peça se encaixa naturalmente. \n Gola canelada com dois botões \n Piqué técnico ventilado ultra-dry e run-resistant \n Color Block em V \n Palavra Lacoste atrás do pescoço e na manga direita \n Transfer do crocodilo, na cor verde \n Poliéster (100%)",R.drawable.product4 ,100,10,e_Sexo.masculino),
            new Product("CAMISA POLO LACOSTE SLIM FIT MASCULINA EM PETIT PIQUÉ","Um item essencial no guarda-roupa desta estação, esta camisa polo é feita com o inconfundível tecido petit piqué de algodão da Lacoste. Fica perfeita com uma calça chino de algodão e um par de tênis da coleção. \n Carcela com 2 botões \n Petit piqué de algodão dois cabos \n Slim fit \n Gola e punhos canelados \n Crocodilo bordado no peito, na cor verde \n Algodão (100%)",R.drawable.product5 ,100,10,e_Sexo.masculino),
            new Product("POLO LACOSTE COLLECTION PARA NOVAK DJOKOVIC – EXCLUSIVA CLAY EDITION","Esta polo técnica feita exclusivamente para Novak Djokovic é perfeita para as quadras de saibro. Parte da nova coleção para o novo ícone da Lacoste, esta polo Lacoste Sport é feita para máxima performance. Vem com uma charmosa estampa gráfica.",R.drawable.product6 ,100,10,e_Sexo.masculino),
            new Product("CAMISA POLO LACOSTE SPORT TENNIS MASCULINA EM PIQUÉ TÉCNICO COM FAIXAS COLORIDAS","Feita em piqué técnico ultraventilado, esta camisa polo Lacoste Sport Tennis ostenta um design gráfico da marca no peito. Ideal para a sua próxima competição. \n Piqué técnico ventilado, resistente, ultra-dry e run-resistant \n Gola polo canelada com dois botões \n Faixas contrastantes bicolores no peito \n Palavra Lacoste da parte detrás da gola e na manga direita \n Transfer verde do crocodilo no peito \n Tecido principal: Poliéster (100%) / Gola: Poliéster (98%), Elastano (2%)",R.drawable.product7 ,100,10,e_Sexo.masculino),
            new Product("CAMISA POLO LACOSTE SPORT MASCULINA EDIÇÃO ROLAND GARROS EM PIQUÉ TÉCNICO ESTAMPADO","Feita em piqué técnico ultrarresistente com uma atraente estampa de rede, esta camisa polo Lacoste Sport dará um refinado toque de Roland Garros à sua próxima partida. \n Piqué técnico ventilado, resistente, ultra-dry e run-resistant \n Gola polo com zíper e borda contrastante \n Acabamentos contrastantes na parte interna da gola \n Logo ultra-dry na barra detrás \n Marca do crocodilo branco bordado e emblema Roland Garros \n Poliéster (100%)",R.drawable.product8 ,100,10,e_Sexo.masculino),
            new Product("POLO LACOSTE COLLECTION PARA NOVAK DJOKOVIC – EXCLUSIVA CLAY EDITION","Esta polo técnica feita exclusivamente para Novak Djokovic é perfeita para as quadras de saibro. Parte da nova coleção para o novo ícone da Lacoste, esta polo Lacoste Sport é feita para máxima performance. Vem com uma charmosa estampa gráfica. \n Jérsei ultra-dry \n Gola unicolor com três botões \n Marca do crocodilo de 3 cm impressa no peito, na cor verde \n Estampa no peito \n Logo de Novak Djokovic na manga \n Poliéster (100%)",R.drawable.product9 ,100,10,e_Sexo.masculino),
            new Product("POLO LACOSTE L.12.12 DE MANGAS LONGAS","Com mangas longas e uma malha grossa em piqué de algodão, esta polo garante conforto e aquecimento. Este item essencial no guarda-roupa masculino dá um charmoso toque casual aos looks cotidianos. \n Gola e punhos canelados \n Vista com dois botões \n Botões de madrepérola \n Classic fit \n Petit piqué de algodão \n Algodão (100%)",R.drawable.product10 ,100,10,e_Sexo.masculino),
            new Product("CAMISETA LACOSTE LIVE UNISSEX EM JÉRSEI DE ALGODÃO COM GOLA REDONDA","Tradicional peça do guarda-roupa Lacoste, esta camiseta unissex Slim Fit é feita com simplicidade e cuidado em jérsei de algodão. Um por todos e todos por um.\n Jérsei de algodão \n Gola redonda \n Slim fit unissex \n Crocodilo bordado no peito, na cor verde \n Algodão (100%)",R.drawable.product11 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA LACOSTE LIVE UNISSEX EM JÉRSEI DE ALGODÃO COM GOLA REDONDA","Tradicional peça do guarda-roupa Lacoste, esta camiseta unissex Slim Fit é feita com simplicidade e cuidado em jérsei de algodão. Um por todos e todos por um. \n Jérsei de algodão \n Gola redonda \n Slim fit unissex \n Crocodilo bordado no peito, na cor verde \n Algodão (100%)",R.drawable.product12 ,100,10,e_Sexo.feminino),
            new Product("T-SHIRT DE DECOTE EM V SLIM FIT EM JERSEY DE ALGODÃO UNICOLOR","Esta t-shirt com decote em V e acabamentos subtis é confecionada em jersey de algodão suave. Um artigo indispensável e elegante do guarda-roupa feminino da estação. \n Decote em V com acabamentos subtis \n Jersey de algodão suave unicolor \n Corte muito justo \n Crocodilo tom sobre tom bordado aplicado no peito \n Algodão (100%)",R.drawable.product13 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA EM MALHA CANELADA COM GOLA HENLEY","Magnífico corte feminino para esta camiseta em malha solta e padrão canelado plano. Possui carcela de botões para um look encantador e fascinante. \n Gola Henley com botões \n Regular fit \n Canelado plano unicolor \n Marca do crocodilo bordada em tom sobre tom no peito \n Raiom (100%)",R.drawable.product14 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA EM MALHA CANELADA COM GOLA HENLEY","Magnífico corte feminino para esta camiseta em malha solta e padrão canelado plano. Possui carcela de botões para um look encantador e fascinante.\n Gola Henley com botões \n Regular fit \n Canelado plano unicolor \n Marca do crocodilo bordada em tom sobre tom no peito \n Raiom (100%)",R.drawable.product15 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA FOLGADA EM MALHA MILANO LISTRADA COM COLOR BLOCKS","Macia e irresistível, esta camiseta folgada em malha Milano apresenta um ousado mix de listras. Combine com uma saia plissada para um look dinâmico. \n Gola redonda \n Regular fit \n Malha Milano listrada leve \n Listras assimétricas em color blocks \n Crocodilo bordado, em tom sobre tom \n Viscose (77%), Poliamida (23%)",R.drawable.product16 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA EM JÉRSEI E CREPE DE ALGODÃO ESTAMPADO COM GOLA REDONDA","Com uma estampa dinâmica em tecido misto de jérsei, crepe e algodão, esta camiseta é um clássico contemporâneo e feminino. Não perca esta peça para o melhor verão da sua vida. \n Gola redonda \n Jérsei crepe de algodão \n Crocodilo bordado com sobreposição de tons \n Algodão (100%)",R.drawable.product17 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA LACOSTE LIVE UNISSEX EM JÉRSEI DE ALGODÃO COM GOLA V", "Feita de jérsei de algodão, esta camiseta Slim Fit Lacoste LIVE apresenta uma clássica gola V que a torna perfeita para usar em camadas e para compartilhar com ele ou com ela. \n Jérsei de algodão unicolor \nGola em V \n Slim fit unissex \n Orla da gola debruada \n Crocodilo bordado no peito, na cor verde \n Algodão (100%)",R.drawable.product18 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA EM JÉRSEI E CREPE DE ALGODÃO ESTAMPADO COM GOLA REDONDA","Com uma estampa dinâmica em tecido misto de jérsei, crepe e algodão, esta camiseta é um clássico contemporâneo e feminino. Não perca esta peça para o melhor verão da sua vida. \n Gola redonda \n Jérsei crepe de algodão \n Crocodilo bordado com sobreposição de tons \n Algodão (100%)",R.drawable.product19 ,100,10,e_Sexo.feminino),
            new Product("CAMISETA FEMININA EM JÉRSEI ESTAMPADO COM GOLA REDONDA E ABERTURA NAS COSTAS","Decorada com uma estampa gráfica, esta camiseta em jérsei possui uma abertura nas costas e um corte fluido para uma versão superfeminina de uma peça moderna. Adorável. \n Gola redonda canelada \n Jérsei de algodão misto \n Abertura nas costas \n Marca do crocodilo tonal bordada \nTecido principal: Lyocell (67%), Algodão (33%) / Gola: Lyocell (64%), Algodão (32%), Elastano (4%)",R.drawable.product20 ,100,10,e_Sexo.feminino)
     };

}
